name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Set up Pylint configuration
      run: |
        echo "
        [MASTER]
        disable=
            missing-function-docstring,  # Disable docstring checks for functions
            missing-class-docstring,     # Disable docstring checks for classes
            missing-module-docstring     # Disable docstring checks for modules
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
